MP-3896 📝 Add tax numbers and organization resource
MyParcelCOM/docs pull request #172
Opened 2020-12-30 22:11 UTC by M4tini

2021-01-04 08:15 UTC, NickVries requested changes
If Scurri asked for documentation on this, were they asking because it was missing, or because they didn't understand something about it?

2021-01-04 08:15 UTC, NickVries commented on content/api/resources/organizations.md
> +vat_number                  | string                                              | VAT identification number of the business.                                 |
Let's use `organization` here, since business may cause some confusion among some users that might think it's something else than the organization.

2021-01-04 14:42 UTC, M4tini commented on content/api/resources/organizations.md
> +vat_number                  | string                                              | VAT identification number of the business.                                 |
Asking because they did not find it when searching for it + I guess the Slack message from Gary / Spring was confusing them. It was resolved by pointing them to the api-specification, but we should include it in the docs for consistency.

2021-01-05 06:39 UTC, NickVries approved these changes

2021-01-05 06:39 UTC, merged