📝 Add fuel_surcharge to service-rate resource
MyParcelCOM/docs pull request #184
Opened 2021-03-22 17:55 UTC by M4tini

I would suggest to hide whitespace when reviewing this PR because of the table indentation.

I also changed some other bits (pending stuff on my local system).

2021-03-23 08:07 UTC, NickVries requested changes

2021-03-23 08:07 UTC, NickVries commented on content/php-sdk/common-use-case.md
> +    );
If you're going to mention that international shipments need items and customs, it would be better to give an example where all required fields are used.

2021-03-24 08:00 UTC, NickVries requested changes

2021-03-24 08:00 UTC, NickVries commented on content/php-sdk/common-use-case.md
>          (new Customs())
What about incoterm and other required properties on the customs object?

2021-03-24 09:34 UTC, M4tini commented on content/php-sdk/common-use-case.md
>          (new Customs())
Whoops, added!

2021-03-24 09:51 UTC, NickVries approved these changes

2021-03-24 09:51 UTC, merged