📝 Document label mime type
MyParcelCOM/docs pull request #201
Opened 2021-07-30 11:04 UTC by M4tini

2021-08-02 09:38 UTC, NickVries requested changes

2021-08-02 09:38 UTC, NickVries commented on content/api/resources/files.md
> +{{% /notice %}}
Isn't this contradiciting what you've said in the `create-a-shipment` page? You mention there that the default mime type will depend on the carrier and most likely will be A6 PDF, while here you say the defualt is always `application/pdf`.

2021-08-03 07:21 UTC, zwaans approved these changes

2021-08-04 08:28 UTC, NickVries approved these changes

2021-08-04 08:28 UTC, merged